import imports

class FSMChoiceBus(imports.StatesGroup):
    choice_city = imports.State()
    choice_station = imports.State()
    choice_side = imports.State()
    choice_bus = imports.State()
    in_bus = imports.State()
    add_city = imports.State()
    add_station = imports.State()
    add_side = imports.State()
    add_bus = imports.State()
    add_in_bus = imports.State()
    delete_city = imports.State()
    delete_station = imports.State()
    delete_side = imports.State()
    delete_bus = imports.State()
    delete_in_bus = imports.State()
    V_POTOKE_ABSOLUTE = imports.State()
    MESSAGE = imports.State()
    BAN = imports.State()
    UNBAN = imports.State()
